---
title: "primates"
author: "Junyi"
date: "22/11/2020"
output: html_document
---
```{r}
library("sf")
library("ggplot2")
library("rnaturalearth")
library("rnaturalearthdata")
library("Factoshiny")
```

```{r}
setwd("C:/Users/mimi/Desktop/M2/Visualisation de données/PROJET/Dataset")
quantitative <- read.csv("ATLANTIC-PR_Quantitative.csv", header = TRUE, sep = ";")
occurrence <- read.csv("ATLANTIC-PR_Occurrence.csv", header = TRUE, sep = ";")
community <- read.csv("ATLANTIC-PR_Community.csv", header = TRUE, sep = ";")
dim(quantitative)
dim(occurrence)
dim(community)

str(occurrence)
str(quantitative)
str(community)
```

essai pour réaliser le fond de carte centré sur l'amérique latine 

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
amerique_dta <- world  %>% filter(name == '')
st_crs(amerique_dta)
amerique_dta%>% ggplot() + geom_sf()


```
```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
st_crs(world )
world %>%   filter(brk_name == "United States") %>% st_transform(crs = 2163) %>% ggplot() + geom_sf()
```


classif sur temperature altitude pluie
```{r}
library(Factoshiny)

dta <- occurrence[,c(4,16:18)]
summary(dta)
Factoshiny(dta)

```
```{r}

dfcompleted <-
	missMDA::imputePCA(dta, ncp = 2, quali.sup = c(1))$completeObs
res.PCA <- PCA(dfcompleted,
							 ncp = 2,
							 quali.sup = c(1),
							 graph = FALSE)
res.HCPC <- HCPC(
	res.PCA,
	nb.clust = 3,
	kk = 100,
	consol = FALSE,
	graph = FALSE
)
plot.HCPC(res.HCPC, choice = 'tree', title = 'Arbre hiérarchique')
plot.HCPC(res.HCPC,
					choice = 'map',
					draw.tree = FALSE,
					title = 'Plan factoriel')
plot.HCPC(
	res.HCPC,
	choice = '3D.map',
	ind.names = FALSE,
	centers.plot = FALSE,
	angle = 60,
	title = 'Arbre hiérarchique sur le plan factoriel'
)
```

étape 3 
```{r}
data_classifie <- as.data.frame(res.HCPC$data.clust)
head(data_classifie)
table(data_classifie$SPECIES, data_classifie$clust)
```
```

```{r}
catdesshiny(dta)
```


ggplot des abondances espèces
```{r}
library(tidyverse)

```

```{r}

donnees <- data.frame(x = c(7,21,112,32,10,5,2,47,23,10,1,13,13,35,8,1,19,3,3,252,7,8,1,4,2,57,12,1,5),
                  y = occurence$SPECIES)

occurrence %>% 
  
summary(occurrence$SPECIES)

```

```{r}
bar <- donnees %>% ggplot()+aes(x=x, y=y)
```

```{r}

```

