---
title: "Conservation des primates de la forêt atlantique d'Amérique du Sud"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
---

```{r library_packages, include=FALSE}
# Packages
library(flexdashboard)
library(ggplot2) ; theme_set(theme_minimal())
library(dplyr) ; options(dplyr.summarise.inform = FALSE)
library(grid) ; library(gridExtra) ; library(ggpubr)
library(plotly)
library(ggmap)
library(htmltools)
```


```{r import_data, include=FALSE}
occurrence <- read.csv("./dataset/ATLANTIC-PR_Occurrence.csv", header = TRUE, sep = ";")

# Suppression des espaces inutiles
occurrence$SPECIES <-
	as.factor(gsub("^\\s+|\\s+$", "", occurrence$SPECIES))

# Sélection de colonnes
occ <- occurrence %>% select(SPECIES,
														 SP_ORIGIN,
														 ALTITUDE,
														 ANNUAL_TEMP,
														 ANNUAL_RAIN,
														 LONGITUDE_X,
														 LATITUDE_Y)
# Altitude : quanti -> classe
occ$ALTITUDE[occ$ALTITUDE < 200] = "Plaine"
occ$ALTITUDE[as.numeric(occ$ALTITUDE) < 1000] = "Basse Montagne"
occ$ALTITUDE[as.numeric(occ$ALTITUDE) >= 1000] = "Haute Montagne"
occ$ALTITUDE <- as.factor(occ$ALTITUDE)
occ <- occ[!is.na(occ$ALTITUDE), ]

# Pluviométrie : quanti -> classe
occ$ANNUAL_RAIN[occ$ANNUAL_RAIN < 1100] = "Sec"
occ$ANNUAL_RAIN[as.numeric(occ$ANNUAL_RAIN) < 1700] = "Moyen"
occ$ANNUAL_RAIN[as.numeric(occ$ANNUAL_RAIN) >= 1700] = "Humide"
occ$ANNUAL_RAIN <- as.factor(occ$ANNUAL_RAIN)
occ <- occ[!is.na(occ$ANNUAL_RAIN), ]

# Suppression des lignes où espèces pas correctes (croisement ou sp. indéterminée)
occ <-
	occ[!(
		as.character(occ$SPECIES) %in% c(
			"Callithrix jacchus X Callithrix aurita",
			"Callithrix jacchus X Callithrix penicillata",
			"Callithrix kuhlii x Callithrix penicillata",
			"Callithrix sp.",
			"Sapajus sp.",
			"Callicebus sp.",
			"Alouatta sp."
		)
	),]
occ$SPECIES <- factor(occ$SPECIES)

# Ajout informations iucn
iucn <- read.csv("./dataset/iucn.csv")
i <- iucn %>% select(scientificName, redlistCategory)
occ <- left_join(occ, i, by = c("SPECIES" = "scientificName"))

# Changement ordre levels
occ$redlistCategory = factor(
	occ$redlistCategory,
	levels = c(
		"Critically Endangered",
		"Endangered",
		"Vulnerable",
		"Near Threatened",
		"Least Concern",
		"Data Deficient"
	)
)
```


```{r find_data, include=FALSE}
nb_especes_autochtones <- nrow(occ %>% 
	select(SPECIES, SP_ORIGIN) %>% 
	filter(SP_ORIGIN == "Autochtone") %>% 
	mutate(SPECIES = factor(SPECIES)) %>% 
	distinct(SPECIES, SP_ORIGIN))

especes_menacees <-  occ %>% 
	select(SPECIES, redlistCategory) %>% 
	filter(
		redlistCategory == "Critically Endangered" |
			redlistCategory == "Endangered"  |
			redlistCategory == "Vulnerable"
	) %>%
	mutate(SPECIES = factor(SPECIES)) %>% 
	distinct(SPECIES)
	
especes_CR <- occ %>% 
	select(SPECIES, redlistCategory) %>% 
	filter(redlistCategory == "Critically Endangered") %>% 
	mutate(SPECIES = factor(SPECIES)) %>% 
	distinct(SPECIES)

especes_endangered <- nrow(
	occ %>%
		select(SPECIES, redlistCategory) %>%
		filter(redlistCategory == "Endangered") %>%
		mutate(SPECIES = factor(SPECIES)) %>%
		distinct(SPECIES)
)

especes_vulnerable <- nrow(
	occ %>%
		select(SPECIES, redlistCategory) %>%
		filter(redlistCategory == "Vulnerable") %>%
		mutate(SPECIES = factor(SPECIES)) %>%
		distinct(SPECIES)
)

```



Types de zones à protéger
=====================================  

Column
-------------------------------------

### Distribution des espèces dans les différents types de milieux
```{r barplots_milieux}
f_sep_donnees <- function(donnees, alti, pluvio) {
  
  # S?lection des donn?es pour pluvio et alti
  dta_plot <- donnees %>%
    filter(ANNUAL_RAIN == pluvio & ALTITUDE == alti) %>%
    group_by(SPECIES, ALTITUDE, ANNUAL_RAIN, redlistCategory) %>%
    summarise(n = n())
  
  # Tri par ordre croissant
  dta_plot$SPECIES = factor(dta_plot$SPECIES,
                            levels = dta_plot$SPECIES[order(dta_plot$n, 
                                                            decreasing = TRUE)])
  
  # Nouvelle colonne avec seulement les levels dans ce sous jeu de donn?es (redlistCategory a tous les levels)
  dta_plot$redlistCategory2 <- factor(dta_plot$redlistCategory)
  
  return(dta_plot)
}
# Fonction plot_palette_specifique pour r?cup?rer la palette de couleur adapt?e au nombre de levels ----
plot_palette_specifique <- function(dta_plot){
  
  # D?finition de la palette de couleurs compl?te
  pal_iucn <- palette(c(
    "#B3343D", # "Critically Endangered",
    "#CF6B48", # "Endangered",
    "#E89E4A", # "Vulnerable",
    "#FFCF45", # "Near Threatened",
    "#438A32", # "Least Concern",
    "#C9C9C9"  # "Data Deficient",
  ))
  
  # Si 2 ou plus levels : on construit une palette.
  if (length(levels(dta_plot$redlistCategory2)) > 1) {
    # Initialisation
    new_pal_values = c()
    
    # Boucle pour r?cup?rer les bons levels
    for (rl2 in 1:length(levels(dta_plot$redlistCategory2))) {
      for (rl1 in 1:length(levels(dta_plot$redlistCategory))) {
        if ((levels(dta_plot$redlistCategory2)[rl2]) == levels(dta_plot$redlistCategory)[rl1]) {
          new_pal_values = c(new_pal_values, pal_iucn[rl1])
        }
      }
    }
    
    # Transformation au format palette
    new_pal = palette(value = new_pal_values)
  }
  
  # Si 1 level seulement : on renvoie une couleur unique.
  else if (length(levels(dta_plot$redlistCategory2)) == 1) {
    for (rl1 in 1:length(levels(dta_plot$redlistCategory))) {
      if ((levels(dta_plot$redlistCategory2)[1]) == levels(dta_plot$redlistCategory)[rl1]) {
        new_pal = pal_iucn[rl1]
      }
    }
  }
  return(new_pal)
}
# Fonction plot_a_p pour obtenir un graphique pour chaque type de donn?es ----
plot_a_p <- function(donnees, alti, pluvio, legende_bool = FALSE){
  
  # On r?cup?re les donn?es sp?cifiques pour alti et pluvio
  dta_plot <- f_sep_donnees(donnees, alti, pluvio)
  # On r?cup?re la palette de couleurs
  new_pal_iucn <- plot_palette_specifique(dta_plot)
  
  # On ajoute des couleurs de fond selon la valeur de pluvio
  if (pluvio == "Sec") {
  	if (alti == "Plaine") {
  		background_color = "#EDE3D8"
  	}
  	else if (alti == "Basse Montagne") {
  		background_color = "#D4CAC1"
  	}
  	else if (alti == "Haute Montagne") {
  		background_color = "#BAB2A9"
  	}
  }
  
  else if (pluvio == "Moyen") {
  	if (alti == "Plaine") {
  		background_color = "#EEF0E6"
  	}
  	else if (alti == "Basse Montagne") {
  		background_color = "#D4D6CE"
  	}
  	else if (alti == "Haute Montagne") {
  		background_color = "#BBBDB5"
  	}
  }
  else if (pluvio == "Humide") {
  	if (alti == "Plaine") {
  		background_color = "#DAEDEA"
  	}
  	else if (alti == "Basse Montagne") {
  		background_color = "#C3D4D1"
  	}
  	else if (alti == "Haute Montagne") {
  		background_color = "#ABBAB8"
  	}
  }
  
  # On cr?? des variables de style pour layout
  axe_x_list <- list(
    title = "",
    zeroline = FALSE,
    showline = FALSE,
    showticklabels = FALSE,
    showgrid = FALSE
  )
  axe_y_list <- list(
    range = c(0, 600),
    title = "",
    zeroline = FALSE,
    showline = FALSE,
    showticklabels = FALSE,
    showgrid = FALSE
  )
  
  # On construit la figure
  l <- list(
  	font = list(
  		family = "sans-serif",
  		size = 15,
  		color = "#000"
  	),
  	bgcolor = "white",
  	yanchor = "top",
  	xanchor = "left",
  	x = 0,
  	y = 1,
  	orientation = "h"
  )
  
  figure = plot_ly(
    dta_plot,
    type = 'bar',
    x =  ~ SPECIES,
    y =  ~ n,
    color =  ~ redlistCategory,
    legendgroup = ~ redlistCategory,
    showlegend = legende_bool,
    colors = new_pal_iucn
  ) %>%
    layout(xaxis = axe_x_list,
           yaxis = axe_y_list,
  paper_bgcolor = background_color,
  plot_bgcolor = background_color,
  legend = l,
  margin=list(l=0, r=11, t=5, b=3))
  
  if (length(levels(dta_plot$redlistCategory2)) == 1) {
  	figure = plot_ly(
  		dta_plot,
  		type = 'bar',
  		x =  ~ SPECIES,
  		y =  ~ n,
  		showlegend = legende_bool,
  		color = new_pal_iucn
  	) %>%
  		layout(
  			xaxis = axe_x_list,
  			yaxis = axe_y_list,
  			paper_bgcolor = background_color,
  			plot_bgcolor = background_color,
  			legend = l,
  			margin = list(
  				l = 0,
  				r = 11,
  				t = 5,
  				b = 3
  			)
  		)
  }
  
  return(figure)
}
# On cr?? les plot ----
# Pluvio = Humide
plot_h_p <- plot_a_p(donnees = occ, pluvio = "Humide", alti = "Plaine")
plot_h_b <- plot_a_p(donnees = occ, pluvio = "Humide", alti = "Basse Montagne")
plot_h_h <- plot_a_p(donnees = occ, pluvio = "Humide", alti = "Haute Montagne", legende_bool = TRUE)
# Pluvio = Moyen
plot_m_p <- plot_a_p(donnees = occ, pluvio = "Moyen", alti = "Plaine")
plot_m_b <- plot_a_p(donnees = occ, pluvio = "Moyen", alti = "Basse Montagne")
plot_m_h <- plot_a_p(donnees = occ, pluvio = "Moyen", alti = "Haute Montagne")
# Pluvio = Sec
plot_s_p <- plot_a_p(donnees = occ, pluvio = "Sec", alti = "Plaine")
plot_s_b <- plot_a_p(donnees = occ, pluvio = "Sec", alti = "Basse Montagne")
plot_s_h <- plot_a_p(donnees = occ, pluvio = "Sec", alti = "Haute Montagne")


s <- "width: 32.3%;
	height: 14.5em;
	display: flex;
	border: solid white;
	justify-content: center;"

s_alti <- "width : 1.8em; height: 14.5em; display: flex;border: solid white; 
	text-align: center; font-family:Arial, Helvetica, sans-serif;
	font-weight:bold;letter-spacing:1px; 
	justify-content: center;
	writing-mode: vertical-rl;
	text-orientation: mixed;
	transform: rotate(180deg);"

s_pluvio <- "width : 32.3%; height: 1.8em; display: flex;border: solid white;font-family:Arial, Helvetica, sans-serif;font-weight:bold;text-align:center;letter-spacing:1px; justify-content: center;"

browsable(
	div(
		style = "display: flex; flex-wrap: wrap; justify-content: center;",
		
		div("Haute Montagne (>1000m)", style = paste0("background: #F0F0F0;", s_alti)),
		div(plot_s_h, style = s),
		div(plot_m_h, style = s),
		div(plot_h_h, style = s),
		
		div("Basse Montagne", style = paste0("background: #F2F2F2;", s_alti)),
		div(plot_s_b, style = s),
		div(plot_m_b, style = s),
		div(plot_h_b, style = s),
		
		div("Plaine (< 200 m)", style = paste0("background: #F5F5F5;", s_alti)),
		div(plot_s_p, style = s),
		div(plot_m_p, style = s),
		div(plot_h_p, style = s),
		
		
		div(style = "width : 1.8em;"),
		div("Sec (< 1100 mm/an)", style = paste0("background: #E0D5C8;",s_pluvio)),
		div("Moyen", style = paste0("background: #EAEBE4;",s_pluvio)),
		div("Humide (> 1700 mm/an)", style = paste0("background: #D9EBE8; ",s_pluvio))
	)
)
```
